export const PLANS = {
  free: {
    name: 'FREE',
    price: 'Grátis',
    description: 'Perfeito para começar',
    features: [
      'Até 50 unidades habitacionais',
      '1 usuário administrador',
      'Cadastro de visitantes com QR Code',
      'Controle de acesso básico',
      'Registro de encomendas',
      'Até 3 espaços comuns',
      'App mobile para moradores',
      'Comunicados (até 10/mês)',
      'Suporte via email (48h)',
    ],
    limitations: [
      'Sem gestão financeira',
      'Sem boletos automáticos',
      'Sem assembleias digitais',
      'Marca d\'água "Powered by GESCON"',
    ],
    cta: 'Começar Grátis',
    popular: false,
  },
  pro: {
    name: 'PRO',
    badge: 'Mais Popular',
    priceRange: 'R$ 149,90 - R$ 799,90',
    priceTiers: [
      { range: 'Até 50 unidades', price: 'R$ 149,90/mês' },
      { range: '51-100 unidades', price: 'R$ 249,90/mês' },
      { range: '101-200 unidades', price: 'R$ 449,90/mês' },
      { range: '201-500 unidades', price: 'R$ 799,90/mês' },
    ],
    description: 'Gestão completa do seu condomínio',
    features: [
      'Unidades ilimitadas',
      'Até 5 usuários administradores',
      '✨ Gestão financeira completa',
      '💳 Boletos automáticos (Asaas)',
      '🎯 Multas incluídas no boleto',
      'Assinaturas recorrentes',
      'Balancetes mensais detalhados',
      'Gestão de funcionários',
      'Controle de fornecedores',
      'Assembleias digitais com votação',
      'Enquetes avançadas',
      'Espaços comuns ilimitados',
      'Reservas com cobrança',
      'Upload ilimitado de documentos',
      'Ocorrências com fotos',
      'Comunicados ilimitados',
      'Segmentação por bloco/apartamento',
      'Até 8 câmeras IP',
      '🚗 Reconhecimento de placas (LPR)',
      'Sem marca d\'água',
      'Suporte prioritário (12h)',
    ],
    cta: 'Começar Agora',
    popular: true,
  },
  premium: {
    name: 'PREMIUM',
    badge: 'Enterprise',
    price: 'R$ 399,90+',
    priceModels: [
      'Fixo: R$ 799,90/mês (até 500 unidades)',
      'Escalável: R$ 399,90 + R$ 1,50/unidade',
      'Enterprise: Sob consulta',
    ],
    description: 'Para administradoras e grandes condomínios',
    features: [
      'Tudo do PRO, mais:',
      '🏢 Múltiplos condomínios',
      'Dashboard consolidado',
      'Relatórios comparativos',
      '🎨 White label completo',
      'Domínio próprio',
      'Cores e logo personalizados',
      '🔌 API aberta para integrações',
      'Webhooks customizados',
      'Integração com ERP',
      '🎥 Câmeras ilimitadas',
      'Reconhecimento de placas (LPR)',
      'Armazenamento em nuvem (add-on)',
      'Reconhecimento facial (equipamento à parte)',
      'Backup diário',
      'SLA de 99.9%',
      'Business Intelligence',
      'Usuários ilimitados',
      'Permissões granulares',
      'Suporte 24/7',
      'Gerente de conta dedicado',
      'Consultoria mensal',
    ],
    cta: 'Falar com Vendas',
    popular: false,
  },
} as const;

export const PRICING_FAQ = [
  {
    question: 'Posso mudar de plano a qualquer momento?',
    answer: 'Sim! Você pode fazer upgrade ou downgrade do seu plano quando quiser. O ajuste é feito proporcionalmente no próximo ciclo de cobrança.',
  },
  {
    question: 'Como funciona o período grátis?',
    answer: 'O plano FREE é gratuito para sempre até 50 unidades. Não pedimos cartão de crédito e você pode usar indefinidamente.',
  },
  {
    question: 'E se eu ultrapassar o limite de unidades?',
    answer: 'Você será notificado e poderá fazer upgrade para o PRO. Não bloqueamos o sistema imediatamente, damos um período de adaptação.',
  },
  {
    question: 'Preciso de cartão de crédito para o FREE?',
    answer: 'Não! O plano FREE não requer cartão de crédito e você pode usar indefinidamente.',
  },
  {
    question: 'Qual o custo dos boletos do Asaas?',
    answer: 'O Asaas cobra R$ 2,00 por boleto pago (R$ 1,00 nos primeiros 3 meses). Este custo é do condomínio. Nossos planos já consideram esta taxa na precificação.',
  },
  {
    question: 'Vocês oferecem teste grátis do PRO?',
    answer: 'Sim! Oferecemos 14 dias de teste grátis do plano PRO sem compromisso.',
  },
  {
    question: 'O que é LPR (Reconhecimento de Placas)?',
    answer: 'LPR (License Plate Recognition) é uma tecnologia que identifica automaticamente placas de veículos através de câmeras. No plano PRO, o sistema reconhece até 8 câmeras com LPR, registrando entrada/saída de veículos automaticamente. No plano PREMIUM, você pode usar câmeras ilimitadas com esta funcionalidade. Ideal para portarias com grande fluxo de veículos.',
  },
] as const;
