name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Adiciona as permissões necessárias para o deploy
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build static site
        # Garanta que seu package.json tenha: "build": "next build && next export"
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: npm run build

      # NOVO PASSO PARA DEBUG: Lista os arquivos após o build
      - name: List build output
        run: ls -R

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # O Next.js exporta para a pasta 'out'
